server:
  port: 10010
spring:
  application:
    name: gateway   #服务，名称
  cloud:
    nacos:
      server-addr: localhost:8848   #nacos地址
    gateway:
      routes:    #路由配置
        - id:  user-service      #id唯一标识
          uri: lb://userservice  #路由目标地址
          predicates:            #路由断言 判断请求是否符合规则
            - Path=/user/**     #判断路径是否以/user开头
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
