server:
  port: 10010
spring:
  application:
    name: gateway   #服务，名称
  cloud:
    nacos:
      server-addr: localhost:8848   #nacos地址
    gateway:
       globalcors: # 全局的跨域处理
            add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
            corsConfigurations:
                '[/**]':
                  allowedOrigins: # 允许哪些网站的跨域请求
                    - "http://localhost:8090"
                    - "http://www.leyou.com"
                  allowedMethods: # 允许的跨域ajax的请求方式
                    - "GET"
                    - "POST"
                    - "DELETE"
                    - "PUT"
                    - "OPTIONS"
                  allowedHeaders: "*" # 允许在请求中携带的头信息
                  allowCredentials: true # 是否允许携带cookie
                  maxAge: 360000 # 这次跨域检测的有效期
       routes:    #路由配置
        - id:  user-service      #id唯一标识
          uri: lb://userservice  #路由目标地址
          predicates:            #路由断言 判断请求是否符合规则
            - Path=/user/**     #判断路径是否以/user开头
          filters:
            - AddRequestHeader=Truth,Itcast is freaking aowsome!
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
